name: Upload to GitHub Release

on:
  workflow_run:
    workflows: ["Build Wheels"]
    types:
      - completed
    tags:
      - '*'

jobs:
  upload-to-release:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' && startsWith(github.ref, 'refs/tags/') }}
    
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        
      - name: Download Artifacts - wheels-ubuntu-latest
        uses: actions/download-artifact@v4
        with:
          name: wheels-ubuntu-latest
          path: ./dist
          run-id: ${{ github.event.workflow_run.id }}
          
      - name: Download Artifacts - wheels-windows-latest
        uses: actions/download-artifact@v4
        with:
          name: wheels-windows-latest
          path: ./dist
          run-id: ${{ github.event.workflow_run.id }}
          
      - name: Download Artifacts - wheels-macos-latest
        uses: actions/download-artifact@v4
        with:
          name: wheels-macos-latest
          path: ./dist
          run-id: ${{ github.event.workflow_run.id }}
          
      - name: Download Artifacts - wheels-ubuntu-latest-aarch64
        uses: actions/download-artifact@v4
        with:
          name: wheels-ubuntu-latest-aarch64
          path: ./dist
          run-id: ${{ github.event.workflow_run.id }}
          
      - name: Download Artifacts - sdist
        uses: actions/download-artifact@v4
        with:
          name: sdist
          path: ./dist
          run-id: ${{ github.event.workflow_run.id }}
      
      - name: Display Downloaded Files
        run: ls -la ./dist
      
      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          files: ./dist/*
          draft: false
          prerelease: false
          fail_on_unmatched_files: false
          generate_release_notes: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
